# Generated by Django 3.1.2 on 2020-10-21 13:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30, verbose_name='Department Name')),
                ('code', models.CharField(max_length=5, verbose_name='Department Code')),
            ],
            options={
                'db_table': 'departments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Job title')),
            ],
            options={
                'db_table': 'job_titles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=60, verbose_name='First Name')),
                ('last_name', models.CharField(default=None, max_length=60, verbose_name='Last Name')),
                ('gender', model_utils.fields.StatusField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=100, no_check_for_status=True)),
                ('nis', models.CharField(default='TESTING', max_length=7, unique=True, verbose_name='National Insurance #')),
                ('trn', models.BigIntegerField(default=111111111, unique=True, verbose_name='Tax Registration #')),
                ('employee_number', models.IntegerField(default=1234, verbose_name='Employee #')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('rate', models.FloatField(default=0, verbose_name='Rate Of Pay')),
                ('department', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.department')),
                ('job_title', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.jobtitle', verbose_name='Job Title')),
            ],
            options={
                'db_table': 'employees',
                'managed': True,
            },
        ),
    ]
