# Generated by Django 3.1.2 on 2020-10-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.IntegerField(verbose_name='Employee #'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=60, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=60, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nis',
            field=models.CharField(max_length=7, unique=True, verbose_name='National Insurance #'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rate',
            field=models.FloatField(verbose_name='Rate Of Pay'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='trn',
            field=models.BigIntegerField(unique=True, verbose_name='Tax Registration #'),
        ),
    ]
