# Generated by Django 3.1.2 on 2020-11-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20201105_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='bank',
            name='transit_no',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
