# Generated by Django 3.1.2 on 2020-11-01 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_employee_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='slug',
        ),
    ]
