# Generated by Django 3.1.2 on 2020-10-21 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20201021_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Bank name')),
                ('short_code', models.CharField(max_length=10, verbose_name='Short code')),
            ],
            options={
                'db_table': 'banks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DutyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Duty Type Name')),
            ],
            options={
                'db_table': 'duty_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Payment Method')),
            ],
            options={
                'db_table': 'payment_methods',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.PositiveIntegerField(verbose_name='Employee #'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='trn',
            field=models.PositiveIntegerField(unique=True, verbose_name='Tax Registration #'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.bank', verbose_name='Banks With'),
        ),
    ]
