# Generated by Django 3.1.2 on 2020-10-21 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20201021_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.paymentmethod', verbose_name='Pay By'),
        ),
    ]
