# Generated by Django 3.1.2 on 2020-11-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_auto_20201103_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
