# Generated by Django 3.1.2 on 2020-10-21 17:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_employee_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rate',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Rate Of Pay'),
        ),
    ]
