# Generated by Django 3.1.2 on 2020-11-13 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_auto_20201113_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employeeallowance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employeededuction',
            name='name',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='name',
        ),
    ]
