# Generated by Django 3.1.2 on 2020-11-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_auto_20201113_0027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatutoryDeduction',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='date_posted',
        ),
    ]
