# Generated by Django 3.1.2 on 2020-10-21 17:42

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_auto_20201021_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='------', max_length=100, no_check_for_status=True),
        ),
    ]
