# Generated by Django 3.1.2 on 2020-10-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_auto_20201021_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_account',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Bank Account Number'),
        ),
    ]
