# Generated by Django 3.1.2 on 2020-11-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_auto_20201114_1424'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeDeduction',
        ),
    ]
