# Generated by Django 3.1.2 on 2020-11-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_delete_employeededuction'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='national_ins_num',
            field=models.CharField(default=11111, max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='tax_reg_num',
            field=models.IntegerField(default=111111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deduction',
            name='employee_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='deduction',
            name='employer_rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='deduction',
            name='is_statutory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deduction',
            name='max_for_year',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='deduction',
            name='short_code',
            field=models.CharField(default=1234, max_length=25, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deduction',
            name='short_description',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
