# Generated by Django 3.1.2 on 2020-10-21 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_auto_20201021_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Pay Period')),
            ],
            options={
                'db_table': 'pay_period',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='payment_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.payperiod'),
        ),
    ]
