# Generated by Django 3.1.2 on 2020-10-22 01:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_auto_20201021_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='payment_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.payperiod', verbose_name='Pay Cycle'),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', models.FloatField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee', verbose_name='Employee')),
            ],
            options={
                'db_table': 'salaries',
                'managed': True,
            },
        ),
    ]
