# Generated by Django 3.1.2 on 2020-11-14 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_deduction_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deduction',
            name='is_active',
        ),
    ]
