# Generated by Django 3.1.2 on 2020-11-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_remove_deduction_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='ded_bef_or_after',
            field=models.BooleanField(default=False, verbose_name='Before Or After Ded?'),
        ),
    ]
