# Generated by Django 3.1.2 on 2020-10-22 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_salary_total_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='Payment Amount')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Taxable Payments')),
                ('taxable', models.BooleanField(default=False, verbose_name='Is taxable?')),
            ],
            options={
                'db_table': 'payments',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='StatutoryDeduction',
        ),
        migrations.AlterModelOptions(
            name='otherdeduction',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='employee',
            name='basic_pay',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Basic Pay'),
        ),
        migrations.AddField(
            model_name='employee',
            name='classification',
            field=models.CharField(blank=0, choices=[('', '-------'), (1, 'Salaried'), (2, 'Hourly'), (3, 'Commissioned')], default=2, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='departure_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Departure Date'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Employment Date'),
        ),
        migrations.AlterModelTable(
            name='otherdeduction',
            table='other_deduction',
        ),
        migrations.AddField(
            model_name='employeepayment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='employeepayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payment', verbose_name='Other Payments'),
        ),
    ]
