# Generated by Django 3.1.2 on 2020-11-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_auto_20201115_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='ded_bef_or_after',
            field=models.CharField(choices=[(1, 'Before'), (2, 'After')], default=False, max_length=5, verbose_name='Before Or After Ded?'),
        ),
    ]
