# Generated by Django 3.1.2 on 2020-10-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_auto_20201022_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Company Name')),
                ('trn', models.PositiveIntegerField(verbose_name='Tax Registration #')),
            ],
            options={
                'db_table': 'companies',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='classification',
        ),
    ]
