# Generated by Django 3.1.2 on 2020-10-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='trn',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Tax Registration #'),
        ),
    ]
