# Generated by Django 3.1.2 on 2020-11-18 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_auto_20201117_0421'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allowance',
            table=None,
        ),
        migrations.AlterModelTable(
            name='bank',
            table=None,
        ),
        migrations.AlterModelTable(
            name='company',
            table=None,
        ),
        migrations.AlterModelTable(
            name='contact',
            table=None,
        ),
        migrations.AlterModelTable(
            name='deduction',
            table=None,
        ),
        migrations.AlterModelTable(
            name='department',
            table=None,
        ),
        migrations.AlterModelTable(
            name='dutytype',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jobtitle',
            table=None,
        ),
        migrations.AlterModelTable(
            name='paymentmethod',
            table=None,
        ),
        migrations.AlterModelTable(
            name='salary',
            table=None,
        ),
    ]
