# Generated by Django 3.1.2 on 2020-10-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_auto_20201026_1817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': True, 'ordering': ['employee_number']},
        ),
        migrations.RemoveField(
            model_name='salary',
            name='holiday_pay',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='total_salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
