# Generated by Django 3.1.2 on 2020-10-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0021_auto_20201027_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
