# Generated by Django 3.1.2 on 2020-11-19 00:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0021_auto_20201119_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='address1',
            field=models.CharField(blank=True, default=None, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address2',
            field=models.CharField(blank=True, default=None, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city_parish',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Clarendon'), (2, 'Manchester'), (3, 'St. Catherine'), (4, 'Portland'), (5, 'St. Ann'), (6, 'Kingston'), (7, 'St. Elizabeth'), (8, 'Westmoreland'), (9, 'St. James'), (10, 'Hanover'), (11, 'Trelawny'), (12, 'St. Mary'), (13, 'St. Andrew'), (14, 'St. Thomas')], default=None, null=True, verbose_name='City/Parish'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(blank=True, default='Jamaica', max_length=160, null=True),
        ),
    ]
