# Generated by Django 3.1.2 on 2020-11-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_auto_20201119_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mobile'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Home Phone:'),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Work Phone'),
        ),
    ]
