# Generated by Django 3.1.2 on 2020-10-29 04:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_salary_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'managed': True, 'ordering': ['employee']},
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_account',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='Bank Account Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Employee #'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='hours_worked',
            field=models.FloatField(default=0),
        ),
    ]
