# Generated by Django 3.1.2 on 2020-11-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0023_auto_20201119_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='ljarrett@coolcorp.com', max_length=254),
            preserve_default=False,
        ),
    ]
