# Generated by Django 3.1.2 on 2020-10-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0024_department_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
    ]
