# Generated by Django 3.1.2 on 2020-10-29 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0025_auto_20201029_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('statutory', models.BooleanField(default=False)),
                ('taxable', models.BooleanField(default=False)),
                ('comment', models.CharField(max_length=160)),
            ],
            options={
                'db_table': 'deductions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Earnings')),
                ('taxable', models.BooleanField(default=False, verbose_name='Is taxable?')),
            ],
            options={
                'db_table': 'earning',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='OtherDeduction',
        ),
        migrations.AlterField(
            model_name='employeepayment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.earning', verbose_name='Other Payments'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
