# Generated by Django 3.1.2 on 2020-10-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0026_auto_20201029_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutoryDeduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.FloatField()),
                ('max_threshold', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='statutory',
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='taxable',
        ),
        migrations.AddField(
            model_name='deduction',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Active?'),
        ),
        migrations.AlterField(
            model_name='earning',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Earnings'),
        ),
    ]
