# Generated by Django 3.1.2 on 2020-11-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0026_auto_20201119_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Middle Name'),
        ),
    ]
