# Generated by Django 3.1.2 on 2020-10-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0027_auto_20201029_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='trn',
        ),
        migrations.AddField(
            model_name='employee',
            name='deductions',
            field=models.ManyToManyField(to='payroll.Deduction'),
        ),
        migrations.AddField(
            model_name='employee',
            name='earnings',
            field=models.ManyToManyField(to='payroll.Earning'),
        ),
    ]
