# Generated by Django 3.1.2 on 2020-11-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0027_employee_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default=None, max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
