# Generated by Django 3.1.2 on 2020-10-30 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0028_auto_20201030_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='deductions',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='earnings',
        ),
    ]
