# Generated by Django 3.1.2 on 2020-11-19 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0029_auto_20201119_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Customer')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TimeSheetDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_in', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_time_out', models.DateTimeField(blank=True, default=None, null=True)),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='payroll.employee')),
                ('time_sheet_header', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='time_sheet_header', to='payroll.timesheetheader')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
