# Generated by Django 3.1.2 on 2020-10-30 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0030_employee_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurring', models.BooleanField(default=False)),
                ('earning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.earning')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeePayment',
        ),
        migrations.AddField(
            model_name='earning',
            name='employees',
            field=models.ManyToManyField(through='payroll.EmployeeEarning', to='payroll.Employee'),
        ),
    ]
