# Generated by Django 3.1.2 on 2020-11-20 02:53

import django.core.validators
from django.db import migrations, models
import payroll.validators


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0030_timesheetdetail_timesheetheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nis',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7), payroll.validators.nis_validator], verbose_name='National Insurance #'),
        ),
    ]
