# Generated by Django 3.1.2 on 2020-10-30 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0031_auto_20201030_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earning',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='employeeearning',
            name='recurring',
        ),
    ]
