# Generated by Django 3.1.2 on 2020-10-31 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0032_auto_20201030_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'managed': True, 'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=5, unique=True, verbose_name='Department Code'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='date_posted',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
