# Generated by Django 3.1.2 on 2020-11-20 03:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0032_auto_20201120_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nis',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('[a-zA-Z]{1}\\d{6}$', 'Exmaple of C893312.')], verbose_name='National Insurance #'),
        ),
    ]
