# Generated by Django 3.1.2 on 2020-10-31 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0033_auto_20201031_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Allowances')),
                ('taxable', models.BooleanField(default=False, verbose_name='Is taxable?')),
            ],
            options={
                'db_table': 'allowance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmployeeAllowance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.allowance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='employeeearning',
            name='earning',
        ),
        migrations.RemoveField(
            model_name='employeeearning',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Earning',
        ),
        migrations.DeleteModel(
            name='EmployeeEarning',
        ),
        migrations.AddField(
            model_name='allowance',
            name='allowances',
            field=models.ManyToManyField(through='payroll.EmployeeAllowance', to='payroll.Employee'),
        ),
    ]
