# Generated by Django 3.1.2 on 2020-11-20 03:09

from django.db import migrations, models
import payroll.validators


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0033_auto_20201120_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nis',
            field=models.CharField(max_length=7, unique=True, validators=[payroll.validators.nis_validator], verbose_name='National Insurance #'),
        ),
    ]
