# Generated by Django 3.1.2 on 2020-11-01 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0034_auto_20201031_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowance',
            name='allowances',
        ),
    ]
