# Generated by Django 3.1.2 on 2020-11-01 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0035_remove_allowance_allowances'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeAllowance',
        ),
    ]
