# Generated by Django 3.1.2 on 2020-11-29 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0036_auto_20201120_0426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'managed': True, 'ordering': ['name']},
        ),
    ]
