# Generated by Django 3.1.2 on 2020-11-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0036_delete_employeeallowance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='allowances',
            field=models.ManyToManyField(to='payroll.Allowance'),
        ),
    ]
