# Generated by Django 3.1.2 on 2020-11-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0038_auto_20201129_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduction',
            name='is_statutory',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
