# Generated by Django 3.1.2 on 2020-11-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0039_auto_20201129_0544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavetype',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='deduction',
            name='is_statutory',
            field=models.BooleanField(default=False, verbose_name='Is Statutory?'),
        ),
    ]
