# Generated by Django 3.1.2 on 2020-12-03 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0041_auto_20201130_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetdetail',
            name='date_time_in',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='timesheetdetail',
            name='date_time_out',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='timesheetdetail',
            name='time_sheet_header',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='has_times', to='payroll.timesheetheader'),
        ),
    ]
