# Generated by Django 3.1.2 on 2020-12-03 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0043_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetheader',
            name='customer',
        ),
        migrations.AddField(
            model_name='timesheetheader',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='timesheetheader',
            name='location',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='payroll.location'),
            preserve_default=False,
        ),
    ]
