# Generated by Django 3.1.2 on 2020-12-10 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0044_auto_20201203_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetdetail',
            name='date_time_in',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='timesheetdetail',
            name='date_time_out',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='timesheetdetail',
            name='time_sheet_header',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='timesheetdetail', to='payroll.timesheetheader'),
        ),
        migrations.AlterField(
            model_name='timesheetheader',
            name='comment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='timesheetheader',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.location'),
        ),
    ]
