# Generated by Django 3.1.2 on 2020-12-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0045_auto_20201210_0324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobtitle',
            options={'managed': True, 'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='timesheetheader',
            name='work_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
