# Generated by Django 3.1.2 on 2020-12-14 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0046_auto_20201214_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetheader',
            name='comment',
        ),
    ]
