# Generated by Django 3.1.2 on 2020-12-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0047_remove_timesheetheader_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'managed': True, 'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='date_from',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='employeeleave',
            name='date_to',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
