# Generated by Django 3.1.2 on 2020-12-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0048_auto_20201216_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetdetail',
            name='date_time_in',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='timesheetdetail',
            name='date_time_out',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
