# Generated by Django 3.1.2 on 2020-12-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0050_auto_20201222_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetdetail',
            name='date_time_in',
            field=models.TimeField(max_length=15),
        ),
        migrations.AlterField(
            model_name='timesheetdetail',
            name='date_time_out',
            field=models.TimeField(max_length=15),
        ),
    ]
