# Generated by Django 3.1.2 on 2020-12-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0051_auto_20201222_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetdetail',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
