# Generated by Django 3.1.2 on 2020-12-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0052_auto_20201222_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetdetail',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timesheetheader',
            name='work_date',
            field=models.DateField(default=None),
        ),
    ]
