# Generated by Django 3.1.2 on 2021-01-17 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0055_auto_20201223_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetheader',
            name='work_date',
            field=models.DateField(default=None, verbose_name='Work Date'),
        ),
        migrations.CreateModel(
            name='EmployeeDeduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('ded_date', models.DateField(null=True, verbose_name='Deduction Date')),
                ('recurring', models.BooleanField(verbose_name='Is recurring?')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeededuction_created_by', to=settings.AUTH_USER_MODEL)),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.deduction')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeededuction_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
