# Generated by Django 3.1.2 on 2021-03-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0056_auto_20210117_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='pay_period_end',
            field=models.DateField(blank=True, null=True, verbose_name='Pay Period End'),
        ),
        migrations.AddField(
            model_name='salary',
            name='pay_period_start',
            field=models.DateField(blank=True, null=True, verbose_name='Pay Period Start'),
        ),
    ]
