# Generated by Django 3.1.2 on 2021-03-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0057_auto_20210313_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeallowance',
            name='paid_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Paid Date'),
        ),
    ]
