# Generated by Django 3.1.2 on 2021-03-14 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0058_employeeallowance_paid_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='pay_period_start',
        ),
    ]
